name: flutter_map_supercluster_example
description: Example for Flutter Map Supercluster

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.7.1
  flutter_map_marker_popup: ^7.0.0
  flutter_map_supercluster:
    path: ../
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AccurateMapIcon
      fonts:
        - asset: fonts/AccurateMapIcon.ttf