name: flutter_map_supercluster_example
description: Example for Flutter Map Supercluster

publish_to: "none"

environment:
  sdk: ^3.8.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map_marker_popup: ^8.0.1
  cupertino_icons: ^1.0.6
  flutter_map: ^8.2.1
  flutter_map_animations: ^0.9.0
  flutter_map_supercluster:
    path: ../
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AccurateMapIcon
      fonts:
        - asset: fonts/AccurateMapIcon.ttf