include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    unawaited_futures: true
    prefer_single_quotes: true
    cancel_subscriptions: true
    avoid_slow_async_io: true
    no_duplicate_case_values: true
    unnecessary_statements: true
    avoid_relative_lib_imports: true
    depend_on_referenced_packages: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

formatter:
  page_width: 180
  trailing_commas: preserve